package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Banios generated by hbm2java
 */
public class Banios extends Servicio implements java.io.Serializable {

    public Banios() {
    }

    public Banios(String id) {
        super(id);
    }

    public Banios(String id, String nombre, BigDecimal costo) {
        super(id, nombre, costo);
    }

}


