package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String idCliente;
     private String nombre;
     private String alias;
     private Date fechaAlta;

    public Clientes() {
    }
    
    public Clientes(String idCliente)
    {
        this.idCliente = idCliente;
    }
	
    public Clientes(String idCliente, String nombre, String alias, Date fechaAlta) {
       this.idCliente = idCliente;
       this.nombre = nombre;
       this.alias = alias;
       this.fechaAlta = fechaAlta;
    }
   
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAlias() {
        return this.alias;
    }
    
    public void setAlias(String alias) {
        this.alias = alias;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Override
    public String toString() {
        return nombre +" - "+ alias;
    }
    
    




}


