package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Coches generated by hbm2java
 */
public class Coches  implements java.io.Serializable {


     private String idCoche;
     private String idCliente;
     private String modelo;
     private String placas;
     private Date fechaAlta;

    public Coches() {
    }

    
    public Coches(String idCoche) {
        this.idCoche = idCoche;
    }
    
    public Coches(String idCoche, String idCliente, String modelo, String placas, Date fechaAlta) {
       this.idCoche = idCoche;
       this.idCliente = idCliente;
       this.modelo = modelo;
       this.placas = placas;
       this.fechaAlta = fechaAlta;
    }
   
    public String getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(String idCoche) {
        this.idCoche = idCoche;
    }
    public String getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(String idCliente) {
        this.idCliente = idCliente;
    }
    public String getModelo() {
        return this.modelo;
    }
    
    public void setModelo(String modelo) {
        this.modelo = modelo;
    }
    public String getPlacas() {
        return this.placas;
    }
    
    public void setPlacas(String placas) {
        this.placas = placas;
    }
    public Date getFechaAlta() {
        return this.fechaAlta;
    }
    
    public void setFechaAlta(Date fechaAlta) {
        this.fechaAlta = fechaAlta;
    }

    @Override
    public String toString() {
        return modelo + placas;
    }
}


