package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1

/**
 * HisServLote generated by hbm2java
 */
public class HisServLote implements java.io.Serializable {

     private Long cns;
     private Long idServicio;
     private Long idLote;
     private String idServicioL;
     private String tiempo;

    public HisServLote() {
    }

    public HisServLote(Long idServicio, Long idLote, String idServicioL, String tiempo) {
       this.idServicio = idServicio;
       this.idLote = idLote;
       this.idServicioL = idServicioL;
       this.tiempo = tiempo;
    }
   
    public Long getCns() {
        return this.cns;
    }
    
    public void setCns(Long cns) {
        this.cns = cns;
    }

    public Long getIdServicio() {
        return idServicio;
    }

    public void setIdServicio(Long idServicio) {
        this.idServicio = idServicio;
    }
         
    public Long getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(Long idLote) {
        this.idLote = idLote;
    }
    public String getIdServicioL() {
        return this.idServicioL;
    }
    
    public void setIdServicioL(String idServicioL) {
        this.idServicioL = idServicioL;
    }
    
    public String getTiempo() {
        return this.tiempo;
    }
    
    public void setTiempo(String tiempo) {
        this.tiempo = tiempo;
    }

}


