package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Lotes generated by hbm2java
 */
public class Lotes  implements java.io.Serializable {


     private Long idLote;
     private String estado;
     private String servicio;
     private Date inicio;

    public Lotes() {
    }

	
    public Lotes(long idLote) {
        this.idLote = idLote;
    }
    public Lotes(long idLote, String estado, String servicio, Date inicio) {
       this.idLote = idLote;
       this.estado = estado;
       this.servicio = servicio;
       this.inicio = inicio;
    }
   
    public Long getIdLote() {
        return this.idLote;
    }
    
    public void setIdLote(Long idLote) {
        this.idLote = idLote;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public String getServicio() {
        return this.servicio;
    }
    
    public void setServicio(String servicio) {
        this.servicio = servicio;
    }
    public Date getInicio() {
        return this.inicio;
    }
    
    public void setInicio(Date inicio) {
        this.inicio = inicio;
    }

    @Override
    public String toString() {
        return "Lotes{" + "idLote=" + idLote + ", estado=" + estado + ", servicio=" + servicio + ", inicio=" + inicio + '}';
    }




}


