package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1

/**
 * ServicioPension generated by hbm2java
 */
public class ServicioPension  implements java.io.Serializable {

     private Long id;
     private Long idServicio;
     private String idCoche;
     private String idPension;
     private boolean activa;

    public ServicioPension() {
    }
	
    public ServicioPension(Long id) {
        this.id = id;
    }
    public ServicioPension(Long idServicio, String idCoche, String idPension) {
       this.idServicio = idServicio;
       this.idCoche = idCoche;
       this.idPension = idPension;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getIdServicio() {
        return idServicio;
    }

    public void setIdServicio(Long idServicio) {
        this.idServicio = idServicio;
    }
   
    public String getIdCoche() {
        return this.idCoche;
    }
    
    public void setIdCoche(String idCoche) {
        this.idCoche = idCoche;
    }
    public String getIdPension() {
        return this.idPension;
    }
    
    public void setIdPension(String idPension) {
        this.idPension = idPension;
    }
    
    public boolean isActiva() {
        return activa;
    }

    public void setActiva(boolean activa) {
        this.activa = activa;
    }   

}


