package com.estacionamiento5.pojos;
// Generated 22/02/2018 08:56:57 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * ServiciosLote generated by hbm2java
 */
public class ServiciosLote extends Servicio implements java.io.Serializable {

    public ServiciosLote() {
    }

    public ServiciosLote(String id) {
        super(id);
    }

    public ServiciosLote(String id, String nombre, BigDecimal costo) {
        super(id, nombre, costo);
    }
    
}


